/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-08-06 21:52:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class advanceSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Bookhaus | Advance Search</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/slider.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/jquery-ui.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/simple-sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<section id=\"page-wrapper\">\r\n");
      out.write("\t\t\t<h3 class=\"heading\">\r\n");
      out.write("\t\t\t\tAdvance Search for\r\n");
      out.write("\t\t\t\t<div class=\"btn-group\" id=\"adv-search-dropdown\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"selected-item\">Books</span><span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#books-tab\">Books</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#music-tab\">Music</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#supplies-tab\">Office Supplies</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#accessories-tab\">Accessories</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t<div id=\"my-tab-content\" class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane active\" id=\"books-tab\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal search-form\" action=\"AdvanceSearch\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-center\">Please enter search criteria for Books and click Search.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-4 filter-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Price Range</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>$5</span> <input id=\"booksPriceFilter\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"span2\" value=\"\" data-slider-min=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-max=\"200\" data-slider-tooltip=\"hide\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-step=\"10\" data-slider-value=\"[5,100]\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-input=\"#booksPrice\" /> <span>$100</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"booksPrice\" value=\"5-100\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Published\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tYear</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>1900</span> <input id=\"booksYearFilter\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"span2\" value=\"\" data-slider-min=\"1900\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-max=\"2014\" data-slider-tooltip=\"hide\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-step=\"2\" data-slider-value=\"[1990, 2010]\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-input=\"#booksYear\" /> <span>2010</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"booksYear\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"1990-01-01_2010-01-01\" name=\"published_date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Sort Order 1</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"sortBy1\" id=\"booksSort1\" data-block=\"#booksSort2, #booksSort3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Sort Order</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price asc\">Price - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price desc\">Price - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"published_date asc\">Year - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"published_date desc\">Year - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"author asc\">Author [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"author desc\">Author [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"title asc\">Title [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"title desc\">Title [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Sort Order 2</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"sortBy2\" id=\"booksSort2\" data-block=\"#booksSort3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Sort Order</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price asc\">Price - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price desc\">Price - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"published_date asc\">Year - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"published_date desc\">Year - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"author asc\">Author [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"author desc\">Author [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"title asc\">Title [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"title desc\">Title [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Sort Order 3</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"sortBy3\" id=\"booksSort3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Sort Order</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price asc\">Price - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price desc\">Price - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"published_date asc\">Year - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"published_date desc\">Year - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"author asc\">Author [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"author desc\">Author [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"title asc\">Title [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"title desc\">Title [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"sortOrder\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"isbn\" class=\"col-sm-3 control-label\">ISBN</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"isbn\" name=\"isbn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"ISBN\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-center\">------------------- OR\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t-------------------</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"title\" class=\"col-sm-3 control-label\">Title</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"title\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"title\" placeholder=\"Title of the book\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"author\" class=\"col-sm-3 control-label\">Author</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"author\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"author\" placeholder=\"Author's Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"publisher\" class=\"col-sm-3 control-label\">Publisher</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"publisher\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"publisher\" placeholder=\"Publisher's Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"col-sm-3 control-label\">Subject</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"genre\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Subject</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"architecture\">Architecture</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"fantasy\">Fantasy</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"fiction\">Fiction</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"science\">Science</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"travel\">Travel</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"description\" class=\"col-sm-3 control-label\">Keywords</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<textarea rows=\"3\" class=\"form-control\" id=\"description\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"description\" placeholder=\"Keywords in Description\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"category\" value=\"Books\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-offset-5 col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Search</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"reset\" class=\"btn btn-primary\">Clear</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane\" id=\"music-tab\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal search-form\" action=\"AdvanceSearch\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-center\">Please enter search criteria for Music and click Search.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-4 filter-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Price Range</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>$5</span> <input id=\"musicPriceFilter\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"span2\" value=\"\" data-slider-min=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-max=\"100\" data-slider-tooltip=\"hide\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-step=\"10\" data-slider-value=\"[5,60]\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-input=\"#musicPrice\" /> <span>$60</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"musicPrice\" value=\"5-60\" name=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Release Year</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>2006</span> <input id=\"musicYearFilter\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"span2\" value=\"\" data-slider-min=\"2000\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-max=\"2014\" data-slider-tooltip=\"hide\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-step=\"1\" data-slider-value=\"[2006, 2012]\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-input=\"#musicYear\" /> <span>2012</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"musicYear\" value=\"2006-2012\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"year\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Sort Order 1</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"sortBy1\"  id=\"musicSort3\" data-block=\"#musicSort1, #musicSort2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Sort Order</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price asc\">Price - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price desc\">Price - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"year asc\">Year - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"year desc\">Year - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"artist asc\">Artist [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"artist desc\">Artist [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"album_title asc\">Album [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"album_title desc\">Album [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Sort Order 2</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"sortBy2\" id=\"musicSort2\" data-block=\"#musicSort1, #musicSort3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Sort Order</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price asc\">Price - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price desc\">Price - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"year asc\">Year - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"year desc\">Year - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"artist asc\">Artist [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"artist desc\">Artist [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"album_title asc\">Album [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"album_title desc\">Album [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Sort Order 3</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"sortBy3\" id=\"musicSort3\" data-block=\"#musicSort1, #musicSort2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Sort Order</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price asc\">Price - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price desc\">Price - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"year asc\">Year - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"year desc\">Year - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"artist asc\">Artist [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"artist desc\">Artist [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"album_title asc\">Album [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"album_title desc\">Album [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"sortOrder\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"album_title\" class=\"col-sm-2 control-label\">Album</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"album_title\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"album_title\" placeholder=\"Album Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"artist\" class=\"col-sm-2 control-label\">Artist</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"artist\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"artist\" placeholder=\"Artist Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"col-sm-2 control-label\">Genre</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"genre\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Genre</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"country\">Country</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"pop\">Pop</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"rock\">Rock</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"description\" class=\"col-sm-2 control-label\">Keywords</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<textarea rows=\"3\" class=\"form-control\" id=\"description\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"description\" placeholder=\"Keywords in Description\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"category\" value=\"Music\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-offset-5 col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Search</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"reset\" class=\"btn btn-primary\">Clear</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane\" id=\"supplies-tab\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal search-form\" action=\"AdvanceSearch\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-center\">Please enter search criteria for Office Supplies and click Search.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-4 filter-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Price Range</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>$5</span> <input id=\"suppliesPriceFilter\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"span2\" value=\"\" data-slider-min=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-max=\"100\" data-slider-tooltip=\"hide\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-step=\"10\" data-slider-value=\"[5,60]\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-input=\"#suppliesPrice\" /> <span>$60</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"suppliesPrice\" value=\"5-60\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Sort Order 1</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"sortBy1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Sort Order</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price asc\">Price - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price desc\">Price - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"item_name asc\">Name [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"item_name desc\">Name [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Sort Order 2</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"sortBy2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Sort Order</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price asc\">Price - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price desc\">Price - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"item_name asc\">Name [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"item_name desc\">Name [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"sortOrder\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"item_name\" class=\"col-sm-2 control-label\">Name</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"item_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"item_name\" placeholder=\"Item Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"description\" class=\"col-sm-2 control-label\">Keywords</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<textarea rows=\"3\" class=\"form-control\" id=\"description\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"description\" placeholder=\"Keywords in Description\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"category\" value=\"Office Supplies\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-offset-5 col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Search</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"reset\" class=\"btn btn-primary\">Clear</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane\" id=\"accessories-tab\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal search-form\" action=\"AdvanceSearch\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-center\">Please enter search criteria for Accessories and click Search.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-4 filter-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Price Range</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>$5</span> <input id=\"accessPriceFilter\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"span2\" value=\"\" data-slider-min=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-max=\"100\" data-slider-tooltip=\"hide\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-slider-step=\"10\" data-slider-value=\"[5,60]\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-input=\"#accessPrice\" /> <span>$60</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"accessPrice\" value=\"5-60\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"price\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Sort Order 1</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"sortBy1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Sort Order</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price asc\">Price - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price desc\">Price - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"name asc\">Name [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"name desc\">Name [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"genre\" class=\"control-label\">Sort Order 2</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"sortBy2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-top: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Sort Order</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price asc\">Price - Ascending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"price desc\">Price - Descending</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"name asc\">Name [A-Z]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"name desc\">Name [Z-A]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"sortOrder\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"name\" class=\"col-sm-2 control-label\">Name</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Item Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"description\" class=\"col-sm-2 control-label\">Keywords</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<textarea rows=\"3\" class=\"form-control\" id=\"description\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"description\" placeholder=\"Keywords in Description\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"category\" value=\"Accessories\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-offset-5 col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Search</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"reset\" class=\"btn btn-primary\">Clear</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- /page wrapper -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--  wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"authorListData\" hidden>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"artistListData\" hidden>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"publisherListData\" hidden>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("\t<script src=\"js/jquery-1.11.1.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-ui.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap-slider.js\"></script>\r\n");
      out.write("\t<script src=\"js/script.js\"></script>\r\n");
      out.write("\t<script src=\"js/advSearch.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /advanceSearch.jsp(474,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("item");
    // /advanceSearch.jsp(474,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/advanceSearch.jsp(474,2) '${authorList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${authorList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /advanceSearch.jsp(479,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("item");
    // /advanceSearch.jsp(479,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/advanceSearch.jsp(479,2) '${artistList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${artistList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /advanceSearch.jsp(485,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("item");
    // /advanceSearch.jsp(485,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/advanceSearch.jsp(485,2) '${publisherList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${publisherList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }
}
