/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-08-06 21:45:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Bookhaus | Home</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"./css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/simple-sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  \t<div id=\"wrapper\">\r\n");
      out.write("  \t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("        <section id=\"page-wrapper\">\r\n");
      out.write("        \t<h3 class=\"heading\">New &amp; Popular Items</h3>\r\n");
      out.write("    \t\t<div class=\"row\">\r\n");
      out.write("            \t<div data-category=\"Books\" class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t                    <div class=\"figure\">\r\n");
      out.write("\t                        <img alt=\"\" src=\"img/B17.png\" class=\"img-responsive\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"brand-name\">\r\n");
      out.write("\t                        <a href=\"ProductDetail?id=1&amp;category=Books\">The Alchemist: a graphic novel</a>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"price\">\r\n");
      out.write("\t                        <p class=\"amount\">Price:\r\n");
      out.write("\t                            <span>$15.0</span>\r\n");
      out.write("\t                        </p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            \t<div data-category=\"Books\" class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t                    <div class=\"figure\">\r\n");
      out.write("\t                        <img alt=\"\" src=\"img/B06.png\" class=\"img-responsive\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"brand-name\">\r\n");
      out.write("\t                        <a href=\"ProductDetail?id=2&amp;category=Books\">The C Programming Language</a>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"price\">\r\n");
      out.write("\t                        <p class=\"amount\">Price:\r\n");
      out.write("\t                            <span>$50.0</span>\r\n");
      out.write("\t                        </p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            \t<div data-category=\"Music\" class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t                    <div class=\"figure\">\r\n");
      out.write("\t                        <img alt=\"\" src=\"img/M07.png\" class=\"img-responsive\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"brand-name\">\r\n");
      out.write("\t                        <a href=\"ProductDetail?id=7&amp;category=Music\">The Piano Guys 2</a>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"price\">\r\n");
      out.write("\t                        <p class=\"amount\">Price:\r\n");
      out.write("\t                            <span>$12.0</span>\r\n");
      out.write("\t                        </p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            \t\r\n");
      out.write("\t\t\t\r\n");
      out.write("            \t<div data-category=\"Books\" class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t                    <div class=\"figure\">\r\n");
      out.write("\t                        <img alt=\"\" src=\"img/B12.png\" class=\"img-responsive\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"brand-name\">\r\n");
      out.write("\t                        <a href=\"ProductDetail?id=9&amp;category=Books\">Harry Potter and the goblet of fire</a>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"price\">\r\n");
      out.write("\t                        <p class=\"amount\">Price:\r\n");
      out.write("\t                            <span>$10.0</span>\r\n");
      out.write("\t                        </p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            \t\r\n");
      out.write("            \t<div data-category=\"Music\" class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t                    <div class=\"figure\">\r\n");
      out.write("\t                        <img alt=\"\" src=\"img/M01.png\" class=\"img-responsive\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"brand-name\">\r\n");
      out.write("\t                        <a href=\"ProductDetail?id=1&amp;category=Music\">The Piano Guys</a>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"price\">\r\n");
      out.write("\t                        <p class=\"amount\">Price:\r\n");
      out.write("\t                            <span>$11.0</span>\r\n");
      out.write("\t                        </p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            \t<div data-category=\"Music\" class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t                    <div class=\"figure\">\r\n");
      out.write("\t                        <img alt=\"\" src=\"img/M03.png\" class=\"img-responsive\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"brand-name\">\r\n");
      out.write("\t                        <a href=\"ProductDetail?id=3&amp;category=Music\">Nothing but the beat: David Guetta</a>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"price\">\r\n");
      out.write("\t                        <p class=\"amount\">Price:\r\n");
      out.write("\t                            <span>$11.0</span>\r\n");
      out.write("\t                        </p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            \t<div data-category=\"Books\" class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t                    <div class=\"figure\">\r\n");
      out.write("\t                        <img alt=\"\" src=\"img/B21.png\" class=\"img-responsive\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"brand-name\">\r\n");
      out.write("\t                        <a href=\"ProductDetail?id=20&amp;category=Books\">Theory of Computer Science: Automata, Languages and Computation</a>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"price\">\r\n");
      out.write("\t                        <p class=\"amount\">Price:\r\n");
      out.write("\t                            <span>$10.0</span>\r\n");
      out.write("\t                        </p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div data-category=\"Office Supplies\" class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t                    <div class=\"figure\">\r\n");
      out.write("\t                        <img alt=\"\" src=\"img/S01.png\" class=\"img-responsive\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"brand-name\">\r\n");
      out.write("\t                        <a href=\"ProductDetail?id=1&amp;category=Office Supplies\">color pen set</a>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"price\">\r\n");
      out.write("\t                        <p class=\"amount\">Price:\r\n");
      out.write("\t                            <span>$20.0</span>\r\n");
      out.write("\t                        </p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </section><!-- /page wrapper -->\r\n");
      out.write("    </div><!--  wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"js/jquery-1.11.1.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/script.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
